
identifier_name:
  min_length: # only min_length
    warning: 2
    error: 2 # only error
  excluded: # excluded via string array
    - ok
    - Name
    - DEFAULT_MIME_TYPE
    - sin_port
    - no_sig_pipe

disabled_rules:
  - line_length
  - statement_position

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - LinuxMain.swift
  - Xcode/Tests/XCTestManifests.swift
  - Tests/XCTestManifests.swift
  - Package.swift
