name: Test OS X Platform
on:
  pull_request:
    branches:
        - stable

jobs:
  Test-OS-X-Platform:
    runs-on: macos-latest
    env:
      TEST_REPORTS: /tmp/test-results
      LANG: en_US.UTF-8
  
    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: 12.0
      - uses: actions/checkout@v2
      - name: Create Test Result Directory
        run: |
            mkdir -p tmp/test-results/
      - name: Run Unit Test - macOS
        run: |
            cd Xcode
            set -o pipefail && xcodebuild test -scheme SwifterMac -sdk macosx -destination "arch=x86_64" | xcpretty -c -r html --output $TEST_REPORTS/macOS.html
      - name: Run Unit Test - iOS
        run: |
            cd Xcode
            set -o pipefail && xcodebuild test -scheme SwifteriOS -sdk iphonesimulator -destination "name=iPhone 8" | xcpretty -c -r html --output $TEST_REPORTS/iOS.html
      - name: Run Unit Test - tvOS
        run: |
            cd Xcode
            set -o pipefail && xcodebuild test -scheme SwiftertvOS -sdk appletvsimulator -destination "name=Apple TV 4K (at 1080p)" | xcpretty -c -r html --output $TEST_REPORTS/tvOS.html
      - name: Run Unit Test - Swift Package Manager
        run: |
            cd Xcode
            swift build && swift test
      - name: Archive Test results
        uses: actions/upload-artifact@v1
        with:
            name: test-results
            path: tmp/test-results